version: '3'
services:
    node1:
        build:
            context: .
        ports:
            - "8080:8080"
            - "8443:8443"
            - "3333:3333"
        environment:
            - PORT=8080
        volumes:
            - ./logs:/app/logs
        restart: unless-stopped
        logging:
          options:
            max-size: "10m"
            max-file: "10"